### PR TITLE
3.1.0

### PR DESCRIPTION
**Pull request by aaronshekey**
Bumps up to 3.1.0

Adds

- `shield`

This thickens stroke widths slightly on the following icons:

- `circle-slash`
- `clock`
- `cloud-upload`
- `cloud-download`
- `dashboard`
- `info`
- `issue-closed`
- `issue`
- `issue-reopened`
- `history`
- `question`
- `search`

Fills `comment-discussion`

Thickens `x` to match `checkmark`

### CODE REVIEW

**Comment by xt0rted** [comment]
When I download the `octicons.zip` files from the releases page for `v3.0.0` and `v3.1.0` there's no files in them, only folders with the file names. I'm on Windows and used both the built-in zip viewer and 7zip with the same results.

capture

**Comment by aaronshekey** [comment]
@xt0rted How about for older versions? @cameronmcefee Thoughts?

**Comment by xt0rted** [comment]
Versions `3.0.0`, `3.0.1`, and `3.1.0` do this, the rest contain the files. I tried downloading with IE, FF, and Chrome.

**Comment by aaronshekey** [comment]
@xt0rted Try downloading those again, will ya? I may have found a bug :smile: Lemme know.

**Comment by cameronmcefee** [comment]
Strange… will investigate.

**Comment by xt0rted** [comment]
@aaronshekey they're working now

**Comment by djch** [comment]
This addresses most of the issues I had with the new designs that I didn't share with anyone yet. :+1:

**Comment by aaronshekey** [comment]
@djch It's tough balancing style / legibility / crisp rendering across every device. Gettin' closer!

**Comment by djch** [comment]
@aaronshekey I'll bet! How much more feedback are you getting now they're shipped to GitHub.com?

**Pull request merged**
